#!/bin/csh

# NAME Cancallative Semigroups and Ore's Quotient Condition

if ($#argv != 2) then
	echo "need 2 args: bin-directory ouput-extension"
	exit(1)
endif

set d=$1
set out=$2

# job quot-comm

$d/mccune -f quot-comm.in > quot-comm.$out

# job quot-np2

$d/mccune -f quot-np2.in > quot-np2.$out

# job quot-xy3a

$d/mccune -f quot-xy3a.in > quot-xy3a.$out

# job quot-xy3b

$d/mccune -f quot-xy3b.in > quot-xy3b.$out

# job quot-general

$d/mccune -f quot-general.in > quot-general.$out


